---

- name: Install 'Development tools' package group
  yum:
    name: "{{ devtools_group }}"
    state: present

- name: Enable Code Ready Repo
  rhsm_repository:
    name: codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-x86_64-rpms
    state: enabled
  when: ansible_distribution_major_version == "8"

- name: Install required Samvera base packages and libraries
  yum:
    name: "{{ base_packages }}"
    state: present

- name: Set-up MySQL yum repository
  include_tasks: setup_mysql_yumrepo.yml

- name: Install MySQL packages
  include_tasks: install_mysql_packages.yml
